TOP=../..

include $(TOP)/configure/CONFIG

TEMPLATES_DIR = makeBaseApp

TEMPLATES += top/Makefile
TEMPLATES += top/configure/CONFIG
TEMPLATES += top/configure/CONFIG_SITE
TEMPLATES += top/configure/Makefile
TEMPLATES += top/configure/RELEASE
TEMPLATES += top/configure/RULES
TEMPLATES += top/configure/RULES.ioc
TEMPLATES += top/configure/RULES_DIRS
TEMPLATES += top/configure/RULES_TOP

TEMPLATES += top/supportApp/Makefile
TEMPLATES += top/supportApp/Db/Makefile
TEMPLATES += top/supportApp/src/Makefile
TEMPLATES += top/supportApp/src/_APPNAME_.dbd

TEMPLATES += top/iocApp/Makefile
TEMPLATES += top/iocApp/Db/Makefile
TEMPLATES += top/iocApp/src/Makefile
TEMPLATES += top/iocApp/src/_APPNAME_Main.cpp

TEMPLATES += top/exampleApp/Makefile
TEMPLATES += top/exampleApp/Db/Makefile
TEMPLATES += top/exampleApp/Db/dbExample1.db
TEMPLATES += top/exampleApp/Db/dbExample2.db
TEMPLATES += top/exampleApp/Db/dbSubExample.db
TEMPLATES += top/exampleApp/Db/user.substitutions
TEMPLATES += top/exampleApp/Db/userHost.substitutions
TEMPLATES += top/exampleApp/src/Makefile
TEMPLATES += top/exampleApp/src/xxxRecord.dbd
TEMPLATES += top/exampleApp/src/xxxRecord.c
TEMPLATES += top/exampleApp/src/devXxxSoft.c
TEMPLATES += top/exampleApp/src/xxxSupport.dbd
TEMPLATES += top/exampleApp/src/sncExample.stt
TEMPLATES += top/exampleApp/src/sncProgram.st
TEMPLATES += top/exampleApp/src/sncExample.dbd
TEMPLATES += top/exampleApp/src/dbSubExample.c
TEMPLATES += top/exampleApp/src/dbSubExample.dbd
TEMPLATES += top/exampleApp/src/_APPNAME_Main.cpp
TEMPLATES += top/exampleApp/src/_APPNAME_Hello.c
TEMPLATES += top/exampleApp/src/_APPNAME_Hello.dbd
TEMPLATES += top/exampleApp/src/initTrace.c
TEMPLATES += top/exampleApp/src/initTrace.dbd

TEMPLATES += top/exampleBoot/Makefile
TEMPLATES += top/exampleBoot/nfsCommands@vxWorks
TEMPLATES += top/exampleBoot/nfsCommands@RTEMS
TEMPLATES += top/exampleBoot/ioc/Makefile@Common
TEMPLATES += top/exampleBoot/ioc/Makefile@vxWorks
TEMPLATES += top/exampleBoot/ioc/Makefile@win32
TEMPLATES += top/exampleBoot/ioc/Makefile@windows
TEMPLATES += top/exampleBoot/ioc/Makefile@cygwin
TEMPLATES += top/exampleBoot/ioc/st.cmd@Common
TEMPLATES += top/exampleBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/exampleBoot/ioc/st.cmd@RTEMS
TEMPLATES += top/exampleBoot/ioc/README@Common
TEMPLATES += top/exampleBoot/ioc/README@vxWorks

TEMPLATES += top/caClientApp/Makefile
TEMPLATES += top/caClientApp/caExample.c
TEMPLATES += top/caClientApp/caMonitor.c

TEMPLATES += top/caServerApp/Makefile
TEMPLATES += top/caServerApp/README
TEMPLATES += top/caServerApp/exAsyncPV.cc
TEMPLATES += top/caServerApp/exChannel.cc
TEMPLATES += top/caServerApp/exPV.cc
TEMPLATES += top/caServerApp/exScalarPV.cc
TEMPLATES += top/caServerApp/exServer.cc
TEMPLATES += top/caServerApp/exServer.h
TEMPLATES += top/caServerApp/exVectorPV.cc
TEMPLATES += top/caServerApp/main.cc
TEMPLATES += top/caServerApp/test.adl
TEMPLATES += top/caServerApp/vxEntry.cc

TEMPLATES += top/iocBoot/Makefile
TEMPLATES += top/iocBoot/nfsCommands@vxWorks
TEMPLATES += top/iocBoot/nfsCommands@RTEMS
TEMPLATES += top/iocBoot/ioc/Makefile@Common
TEMPLATES += top/iocBoot/ioc/Makefile@vxWorks
TEMPLATES += top/iocBoot/ioc/Makefile@win32
TEMPLATES += top/iocBoot/ioc/Makefile@windows
TEMPLATES += top/iocBoot/ioc/Makefile@cygwin
TEMPLATES += top/iocBoot/ioc/st.cmd@Common
TEMPLATES += top/iocBoot/ioc/st.cmd@Cross
TEMPLATES += top/iocBoot/ioc/st.cmd@vxWorks
TEMPLATES += top/iocBoot/ioc/st.cmd@RTEMS

# "dlsApp" and "dlsBoot" are empty template directories
# which just contain Makefiles

TEMPLATES += top/dlsApp/Makefile
TEMPLATES += top/dlsApp/Db/Makefile
TEMPLATES += top/dlsApp/src/Makefile
TEMPLATES += top/dlsApp/src/_APPNAME_Main.cpp
TEMPLATES += top/dlsApp/opi/Makefile
TEMPLATES += top/dlsApp/opi/edl/Makefile
TEMPLATES += top/dlsApp/opi/symbol/Makefile
TEMPLATES += top/dlsApp/protocol/Makefile

TEMPLATES += top/dlsBoot/Makefile
TEMPLATES += top/dlsBoot/ioc/Makefile@Common
TEMPLATES += top/dlsBoot/ioc/st_APPNAME_.src@Common
TEMPLATES += top/dlsBoot/ioc/README@Common

# "dlsExampleApp" and "dlsExampleBoot" are the standard
# examples which come with "makeBaseApp" but they have
# the build of the startup script from source (st.src)
# added.

TEMPLATES += top/dlsExampleApp/Makefile
TEMPLATES += top/dlsExampleApp/Db/Makefile
TEMPLATES += top/dlsExampleApp/Db/dbExample1.db
TEMPLATES += top/dlsExampleApp/Db/dbExample2.db
TEMPLATES += top/dlsExampleApp/Db/dbSubExample.db
TEMPLATES += top/dlsExampleApp/src/Makefile
TEMPLATES += top/dlsExampleApp/src/xxxRecord.dbd
TEMPLATES += top/dlsExampleApp/src/xxxRecord.c
TEMPLATES += top/dlsExampleApp/src/devXxxSoft.c
TEMPLATES += top/dlsExampleApp/src/xxxSupport.dbd
TEMPLATES += top/dlsExampleApp/src/sncExample.stt
TEMPLATES += top/dlsExampleApp/src/sncProgram.st
TEMPLATES += top/dlsExampleApp/src/sncExample.dbd
TEMPLATES += top/dlsExampleApp/src/dbSubExample.c
TEMPLATES += top/dlsExampleApp/src/dbSubExample.dbd
TEMPLATES += top/dlsExampleApp/src/_APPNAME_Main.cpp
TEMPLATES += top/dlsExampleApp/opi/Makefile
TEMPLATES += top/dlsExampleApp/opi/edl/Makefile
TEMPLATES += top/dlsExampleApp/opi/symbol/Makefile

TEMPLATES += top/dlsExampleBoot/Makefile
TEMPLATES += top/dlsExampleBoot/ioc/Makefile@Common
TEMPLATES += top/dlsExampleBoot/ioc/st_APPNAME_.src@Common
TEMPLATES += top/dlsExampleBoot/ioc/README@Common

# dlsBLApp is used for building the special cross-technical area BL ioc module.
TEMPLATES += top/dlsBLApp/Makefile
TEMPLATES += top/dlsBLApp/src/Makefile
TEMPLATES += top/dlsBLApp/opi/Makefile
TEMPLATES += top/dlsBLApp/opi/edl/_APPNAME_-hardware-status.edl
TEMPLATES += top/dlsBLApp/opi/edl/_APPNAME_-help.edl
TEMPLATES += top/dlsBLApp/opi/edl/_APPNAME_-interlocks.edl
TEMPLATES += top/dlsBLApp/opi/edl/_APPNAME_-status.edl
TEMPLATES += top/dlsBLApp/opi/edl/_APPNAME_-synoptic.edl
TEMPLATES += top/dlsBLApp/opi/edl/_APPNAME_-overview-src.edl
TEMPLATES += top/dlsBLApp/opi/edl/Makefile

SCRIPTS_HOST += makeBaseApp.pl

include $(TOP)/configure/RULES

