#!/bin/bash

# vendor-import script
# $Revision$
# $Author$

# Arguments
# $1 path to directory containing source
# $2 name of module
# $3 vendor version string

function usage() {
    echo "$(basename $0) <path to import from> <module name> <vendor version>"
}

if [ $# != 3 ]; then
    usage
    exit
fi

if [ "x$SVN_ROOT" == "x" ]; then
    echo "SVN_ROOT environment variable must be set"
    exit
fi

# Check for existence of this module in various places in the repository
svn list $SVN_ROOT/diamond/release/support/$2 >/dev/null 2>&1
REL_OK=$?
svn list $SVN_ROOT/diamond/vendor/support/$2 >/dev/null 2>&1
VEND_OK=$?
svn list $SVN_ROOT/diamond/trunk/support/$2 >/dev/null 2>&1
TRUNK_OK=$?

if [ $REL_OK -eq 0 -o $VEND_OK -eq 0 -o $TRUNK_OK -eq 0 ]; then
    echo "Repository already contains the $2 module. Sorry!"
    exit;
fi

echo "Importing vendor source from $1"
svn import --quiet $1 $SVN_ROOT/diamond/vendor/support/$2/current -m "Import of $2 from pristine $3 source"

echo "Tagging vendor source at version $3"
svn copy $SVN_ROOT/diamond/vendor/support/$2/current $SVN_ROOT/diamond/vendor/support/$2/$3 -m "Tagged $2 $3 vendor drop"

echo "Copying vendor source to trunk"
svn copy $SVN_ROOT/diamond/vendor/support/$2/current $SVN_ROOT/diamond/trunk/support/$2 -m "Initial copy of $2 $3 to trunk"

echo "Checking out trunk..."
svn checkout --quiet $SVN_ROOT/diamond/trunk/support/$2

echo "Please now edit configure/RELEASE to put in correct paths"
echo " use make to check that it builds, then commit with the following comment:"
echo " \"$2: changed configure/RELEASE to reflect diamond paths\""



