#!/bin/bash

# list branches script
# $Revision$
# $Author$

# Arguments
# $1 name of module

function usage() {
    echo "$(basename $0)"
}

if [ "x$SVN_ROOT" == "x" ]; then
    echo "SVN_ROOT environment variable must be set"
    exit
fi

MODULES=$(svn list $SVN_ROOT/diamond/trunk/support 2> /dev/null)
if [ $? -ne 0 ]; then
    echo "No modules exist in diamond/support!! Serious problem!"
else
    echo "The following modules exist under diamond/support:"
    echo "$MODULES" | sed -e 's#/##g'
fi
